config/routes.rb
Dutchauction::Application.routes.draw do

  resource  :user do
    resources :purchases, only: []
  end

  resource  :session, only: [:new, :create, :destroy]
  resources :auctions, only: [:index, :show] do
    resource  :purchase, only: [:new, :create, :show] do
      post :reserve
    end
    resource  :auction_participation, only: [:create]
  end

  namespace :administration do
    resources :users

    resources :auctions do
      put :schedule
      put :unschedule
      put :start
      put :wait_for_active_users
      put :reach_lowest_price
      put :terminate
      put :sell_out
    end

    resources :purchases
  end

  root to: "auctions#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :name, :surname

  has_secure_password

  # Associations
  has_many :auction_participations
  has_many :auctions, :through => :auction_participations

  # States
  state_machine :state, :initial => :new do

    state :new
    state :awaiting_confirmation
    state :confirmed
    state :active
    state :disabled
    state :banned

    event :wait_for_confirmation do
      transition [:new] => :awaiting_confirmation
    end

    event :confirm do
      transition [:awaiting_confirmation] => :confirmed
    end

    event :activate do
      transition [:new, :awaiting_confirmation, :confirmed, :disabled, :banned] => :active
    end

    event :disable do
      transition [:active] => :disabled
    end

    event :ban do
      transition [:active] => :banned
    end

  end

  # Validations
  # Class methods
  # Instance methods

  def registered_for?(auction)
    self.auctions.include? auction
  end
end

app/controllers/administration/auctions_controller.rb
class Administration::AuctionsController < Administration::CommonController

  def index
    @auctions = Auction.all
  end

  def show
    @auction = Auction.find(params[:id])

    respond_to do |format|
      format.html {}
      format.js   {}
    end
  end

  def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new(params[:auction])

    if @auction.save
      redirect_to administration_auctions_path, notice: 'Auction created'
    else
      flash.now[:error] = 'Auction not created'
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def schedule
    @auction = Auction.find(params[:auction_id])
    @auction.schedule
    redirect_to administration_auction_path(@auction)
  end

  def unschedule
    @auction = Auction.find(params[:auction_id])
    @auction.unschedule
    redirect_to administration_auction_path(@auction)
  end

  def start
    @auction = Auction.find(params[:auction_id])
    @auction.start
    redirect_to administration_auction_path(@auction)
  end

  def wait_for_active_users
    @auction = Auction.find(params[:auction_id])
    @auction.wait_for_active_users
    redirect_to administration_auction_path(@auction)
  end

  def reach_lowest_price
    @auction = Auction.find(params[:auction_id])
    @auction.reach_lowest_price
    redirect_to administration_auction_path(@auction)
  end

  def terminate
    @auction = Auction.find(params[:auction_id])
    @auction.terminate
    redirect_to administration_auction_path(@auction)
  end

  def sell_out
    @auction = Auction.find(params[:auction_id])
    @auction.sell_out
    redirect_to administration_auction_path(@auction)
  end

end

app/controllers/administration/common_controller.rb
class Administration::CommonController < ApplicationController
end

app/controllers/administration/purchases_controller.rb
class Administration::PurchasesController < Administration::CommonController

  def index
    @purchases = Purchase.all
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/administration/users_controller.rb
class Administration::UsersController < Administration::CommonController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to administration_users_path, notice: 'User created'
    else
      flash.now[:error] = 'User not created'
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :require_login, only: ['show', 'edit', 'update']

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new params[:user]

    if @user.save
      log_in(@user)
      redirect_to back_or_default(user_path)
    else
      flash.now[:error] = 'Invalid form data'
      render :action => 'new'
    end
  end

  def edit
  end

  def update
  end

end

app/views/administration/users/_form.html.erb
_form.html.erb

app/views/administration/users/index.html.erb
<table border="1">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Surname</th>
      <th>Email</th>
      <th>State</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.surname %></td>
        <td><%= user.email %></td>
        <td><%= user.state %></td>
        <td><%= user.created_at %></td>
        <td><%= user.updated_at %></td>
        <td>Edit</td>
        <td>Delete</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New', new_administration_user_path %>

app/views/administration/users/new.html.erb
<%= form_for [:administration, @user] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br/><br/>

  <%= f.label :surname %>
  <%= f.text_field :surname %>
  <br/><br/>

  <%= f.label :email %>
  <%= f.text_field :email %>
  <br/><br/>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br/><br/>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br/><br/>

  <%= f.submit :create %>
<% end %>