config/routes.rb
Dutchauction::Application.routes.draw do

  resource  :user do
    resources :purchases, only: []
  end

  resource  :session, only: [:new, :create, :destroy]
  resources :auctions, only: [:index, :show] do
    resource  :purchase, only: [:new, :create, :show] do
      post :reserve
    end
    resource  :auction_participation, only: [:create]
  end

  namespace :administration do
    resources :users

    resources :auctions do
      put :schedule
      put :unschedule
      put :start
      put :wait_for_active_users
      put :reach_lowest_price
      put :terminate
      put :sell_out
    end

    resources :purchases
  end

  root to: "auctions#index"
end

app/models/auction.rb
class Auction < ActiveRecord::Base
  attr_accessible :title, :description,
                  :start_price, :end_price, :current_price, :store_price,
                  :start_quantity, :current_quantity,
                  :minimum_users_per_product, :maximum_users_per_product,
                  :time_for_purchase, # in seconds
                  :start_datetime,
                  :active_users_timeout, :wait_for_active_users_until,
                  :price_reduce_amount, :price_reduce_pace, :next_price_reduce_at
  # Associations
  has_many :purchases

  has_many :auction_participations
  has_many :users, :through => :auction_participations

  # States
  state_machine :state, :initial => :unscheduled do

    state :unscheduled
    state :scheduled
    state :running
    state :waiting_for_active_users
    state :reached_lowest_price
    state :terminated
    state :sold_out

    event :schedule do
      transition [:unscheduled] => :scheduled
    end

    event :unschedule do
      transition [:scheduled] => :unscheduled
    end

    event :start do
      transition [:waiting_for_active_users, :scheduled] => :running
    end

    event :wait_for_active_users do
      transition [:running] => :waiting_for_active_users
    end

    event :reach_lowest_price do
      transition [:running] => :reached_lowest_price
    end

    event :terminate do
      transition [:running, :waiting_for_active_users] => :terminated
    end

    event :sell_out do
      transition [:running] => :sold_out
    end

  end

  # Callbacks
  before_save :default_values

  # Validations
  # Class methods
  # Instance methods

  def active_users_count
    auction_participations.active.count
  end

  def inactive_users_count
    auction_participations.inactive.count
  end

  def users_count
    auction_participations.count
  end

  def minimum_active_users_count
    minimum_users_per_product * current_quantity
  end

  def seconds_till_start
    (start_datetime - Time.now).to_i.tap { |s| s > 0 ? s : 0 }
  end

  def seconds_till_next_price_reduce
    if next_price_reduce_at.nil?
      0
    else
      (next_price_reduce_at - Time.now).to_i.tap { |s| s > 0 ? s : 0 }
    end
  end

  def seconds_till_end_due_not_enough_active_users
    (wait_for_active_users_until - Time.now).to_i.tap { |s| s > 0 ? s : 0 }
  end

  private 

  def default_values
    self.current_price    ||= self.start_price
    self.current_quantity ||= self.start_quantity
  end
end

app/controllers/administration/auctions_controller.rb
class Administration::AuctionsController < Administration::CommonController

  def index
    @auctions = Auction.all
  end

  def show
    @auction = Auction.find(params[:id])

    respond_to do |format|
      format.html {}
      format.js   {}
    end
  end

  def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new(params[:auction])

    if @auction.save
      redirect_to administration_auctions_path, notice: 'Auction created'
    else
      flash.now[:error] = 'Auction not created'
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def schedule
    @auction = Auction.find(params[:auction_id])
    @auction.schedule
    redirect_to administration_auction_path(@auction)
  end

  def unschedule
    @auction = Auction.find(params[:auction_id])
    @auction.unschedule
    redirect_to administration_auction_path(@auction)
  end

  def start
    @auction = Auction.find(params[:auction_id])
    @auction.start
    redirect_to administration_auction_path(@auction)
  end

  def wait_for_active_users
    @auction = Auction.find(params[:auction_id])
    @auction.wait_for_active_users
    redirect_to administration_auction_path(@auction)
  end

  def reach_lowest_price
    @auction = Auction.find(params[:auction_id])
    @auction.reach_lowest_price
    redirect_to administration_auction_path(@auction)
  end

  def terminate
    @auction = Auction.find(params[:auction_id])
    @auction.terminate
    redirect_to administration_auction_path(@auction)
  end

  def sell_out
    @auction = Auction.find(params[:auction_id])
    @auction.sell_out
    redirect_to administration_auction_path(@auction)
  end

end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController

  def index
    @auctions = Auction.all
  end

  def show
    @auction = Auction.find(params[:id])

    respond_to do |format|
      format.html {}
      format.js   {}
    end
  end

end

app/helpers/auctions_helper.rb
module AuctionsHelper

  def state_message_for(auction)
    if logged_in?
      if current_user.registered_for?(auction)
        if true # Add user active in auction check
          authorized_message_for(auction.state)
        else
          'Your participation in this auction has ended.'
        end
      else
        unauthorized_message_for(auction.state)
      end
    else
      unauthorized_message_for(auction.state)
    end
  end

  def authorized_message_for(state)
    case state
    when 'unscheduled'
      'Auction still not scheduled.'
    when 'scheduled'
      'Registered for auction. Waiting to start...'
    when 'running'
      'Auction running...'
    when 'waiting_for_active_users'
      'Waiting for active users ...'
    when 'reached_lowest_price'
      'Auction closed. Product lowest price reached.'
    when 'sold_out'
      'Auction closed. Product sold out.'
    when 'terminated'
      'Auction closed.'
    end
  end

  def unauthorized_message_for(state)
    case state
    when 'unscheduled'
      'Auction not scheduled.'
    when 'scheduled'
      'Registering for auction ...'
    when 'running'
      'Auction is running ...'
    when 'waiting_for_active_users'
      'Auction is running ...'
    when 'reached_lowest_price'
      'Auction closed.'
    when 'sold_out'
      'Auction closed.'
    when 'terminated'
      'Auction closed.'
    end
  end

end

app/views/auctions/_auction.html.erb
<ul class="auction" data-id="<%= auction.id %>" data-url="<%= current_path %>">
  <li class="title"><h1><%= auction.title %></h1></li>
  <li class="description"><%= auction.description %></li>
  <% unless auction.unscheduled? %>
    <li class="start-date">
      Auction starts: <strong><%= auction.start_datetime %></strong>
      <% if auction.scheduled? %>
        ( starts in <%= auction.seconds_till_start/3600/24 %>d 
        <%= Time.at(auction.seconds_till_start).gmtime.strftime('%Hh %Mmin %Ssec') %> )
      <% end %>
    </li>
  <% end %>
  <li class="store-price">Store price: <strong><%= '%.2f' % auction.store_price %> BGN</strong></li>
  <li class="start-price">Start price: <strong><%= '%.2f' % auction.start_price %> BGN</strong></li>
  <li class="end-price">End price: <strong><%= '%.2f' % auction.end_price %> BGN</strong></li>
  <li class="current-price">
    Current price: <strong><%= '%.2f' % auction.current_price %> BGN</strong>
    <% if auction.running? %>
      ( next reduce <%= Time.at(auction.seconds_till_next_price_reduce).gmtime.strftime('%Hh %Mmin %Ssec') %> )
    <% end %>
  </li>
  <li class="start-quantity">Start quantity: <strong><%= auction.start_quantity %></strong></li>
  <li class="current-quantity">Current quantity: <strong><%= auction.current_quantity %></strong></li>
  <li class="minimum-users-per-product">Minimum users per product: <strong><%= auction.minimum_users_per_product %></strong></li>
  <li class="maximum-users-per-product">Maximum users per product: <strong><%= auction.maximum_users_per_product %></strong></li>
  <li class="minimum-users-for-auction">Minimum users for auction: <strong><%= auction.minimum_active_users_count %></strong></li>
  <li class="time-for-purchase">Time for purchase: <strong><%= auction.time_for_purchase %> seconds</strong></li>
  <li class="active-users-timeout">
    Active users timeout: <strong><%= auction.active_users_timeout %> seconds</strong>
    <% if auction.waiting_for_active_users? %>
      ( ends in <%= Time.at(auction.seconds_till_end_due_not_enough_active_users).gmtime.strftime('%Hh %Mmin %Ssec') %> )
    <% end %>
  </li>
  <li class="registered-users">Registered users: <strong><%= auction.users.count %></strong></li>
  <li class="active-users">Active users: <strong><%= auction.active_users_count %></strong></li>
  <li class="inactive-users">Inactive users: <strong><%= auction.inactive_users_count %></strong></li>
</ul>

app/views/auctions/_auction_actions.html.erb
<ul class="auction-actions">
  <% if logged_in? %>
    <% if current_user.registered_for?(auction) %> <%# Add user active in auction check %>
      <% if true %> <%# Add user active in auction check %>
        <% if auction.scheduled? %>
          <%# Do not show anything %>
        <% elsif auction.running? %>
          <li><%= button_to 'Buy', reserve_auction_purchase_path(auction) %></li>
        <% elsif auction.waiting_for_active_users? %>
          <%# Do not show anything %>
        <% elsif auction.reached_lowest_price? %>
          <%# Do not show anything %>
        <% elsif auction.sold_out? %>
          <%# Do not show anything %>
        <% elsif auction.terminated? %>
          <%# Do not show anything %>
        <% elsif auction.unscheduled? %>
          <%# Do not show anything %>
        <% end %>
      <% else %>
        <%# Do not show anything %>
      <% end %>
    <% else %>
      <% if auction.scheduled? %>
        <li><%= button_to 'Register for auction', auction_auction_participation_path(auction) %></li>
      <% end %>
    <% end %>
  <% else %>
    <li><%= link_to 'Sign in', new_session_path(referrer_param => current_path) %></li>
    <li><%= link_to 'Sign up', new_user_path(referrer_param => current_path) %></li>
  <% end %>  
</ul>

app/views/auctions/_auction_state.html.erb
<%= content_tag :div, class: "auction-state is-#{auction.state.dasherize}" do %>
  <%= state_message_for(auction) %>
<% end %>

app/views/auctions/index.html.erb
<ul>
  <% @auctions.each do |auction| %>
    <li><%= link_to auction.title, auction_path(auction) %></li>
  <% end %>
</ul>

app/views/auctions/show.html.erb
<%= render partial: 'auction_state',  locals: { auction: @auction } %>
<%= render partial: 'auction',         locals: { auction: @auction } %>
<%= render partial: 'auction_actions', locals: { auction: @auction } %>

app/views/auctions/show.js.erb
$('.auction-state').replaceWith('<%=j render partial: 'auction_state', locals: { auction: @auction } %>');
$('.auction').replaceWith('<%=j render partial: 'auction', locals: { auction: @auction } %>');
$('.auction-actions').replaceWith('<%=j render partial: 'auction_actions', locals: { auction: @auction } %>');