config/routes.rb
Dutchauction::Application.routes.draw do

  resource  :user do
    resources :purchases, only: []
  end

  resource  :session, only: [:new, :create, :destroy]
  resources :auctions, only: [:index, :show] do
    resource  :purchase, only: [:new, :create, :show] do
      post :reserve
    end
    resource  :auction_participation, only: [:create]
  end

  namespace :administration do
    resources :users

    resources :auctions do
      put :schedule
      put :unschedule
      put :start
      put :wait_for_active_users
      put :reach_lowest_price
      put :terminate
      put :sell_out
    end

    resources :purchases
  end

  root to: "auctions#index"
end

app/models/auction.rb
class Auction < ActiveRecord::Base
  attr_accessible :title, :description,
                  :start_price, :end_price, :current_price, :store_price,
                  :start_quantity, :current_quantity,
                  :minimum_users_per_product, :maximum_users_per_product,
                  :time_for_purchase, # in seconds
                  :start_datetime,
                  :active_users_timeout, :wait_for_active_users_until,
                  :price_reduce_amount, :price_reduce_pace, :next_price_reduce_at
  # Associations
  has_many :purchases

  has_many :auction_participations
  has_many :users, :through => :auction_participations

  # States
  state_machine :state, :initial => :unscheduled do

    state :unscheduled
    state :scheduled
    state :running
    state :waiting_for_active_users
    state :reached_lowest_price
    state :terminated
    state :sold_out

    event :schedule do
      transition [:unscheduled] => :scheduled
    end

    event :unschedule do
      transition [:scheduled] => :unscheduled
    end

    event :start do
      transition [:waiting_for_active_users, :scheduled] => :running
    end

    event :wait_for_active_users do
      transition [:running] => :waiting_for_active_users
    end

    event :reach_lowest_price do
      transition [:running] => :reached_lowest_price
    end

    event :terminate do
      transition [:running, :waiting_for_active_users] => :terminated
    end

    event :sell_out do
      transition [:running] => :sold_out
    end

  end

  # Callbacks
  before_save :default_values

  # Validations
  # Class methods
  # Instance methods

  def active_users_count
    auction_participations.active.count
  end

  def inactive_users_count
    auction_participations.inactive.count
  end

  def users_count
    auction_participations.count
  end

  def minimum_active_users_count
    minimum_users_per_product * current_quantity
  end

  def seconds_till_start
    (start_datetime - Time.now).to_i.tap { |s| s > 0 ? s : 0 }
  end

  def seconds_till_next_price_reduce
    if next_price_reduce_at.nil?
      0
    else
      (next_price_reduce_at - Time.now).to_i.tap { |s| s > 0 ? s : 0 }
    end
  end

  def seconds_till_end_due_not_enough_active_users
    (wait_for_active_users_until - Time.now).to_i.tap { |s| s > 0 ? s : 0 }
  end

  private 

  def default_values
    self.current_price    ||= self.start_price
    self.current_quantity ||= self.start_quantity
  end
end

app/controllers/administration/auctions_controller.rb
class Administration::AuctionsController < Administration::CommonController

  def index
    @auctions = Auction.all
  end

  def show
    @auction = Auction.find(params[:id])

    respond_to do |format|
      format.html {}
      format.js   {}
    end
  end

  def new
    @auction = Auction.new
  end

  def create
    @auction = Auction.new(params[:auction])

    if @auction.save
      redirect_to administration_auctions_path, notice: 'Auction created'
    else
      flash.now[:error] = 'Auction not created'
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def schedule
    @auction = Auction.find(params[:auction_id])
    @auction.schedule
    redirect_to administration_auction_path(@auction)
  end

  def unschedule
    @auction = Auction.find(params[:auction_id])
    @auction.unschedule
    redirect_to administration_auction_path(@auction)
  end

  def start
    @auction = Auction.find(params[:auction_id])
    @auction.start
    redirect_to administration_auction_path(@auction)
  end

  def wait_for_active_users
    @auction = Auction.find(params[:auction_id])
    @auction.wait_for_active_users
    redirect_to administration_auction_path(@auction)
  end

  def reach_lowest_price
    @auction = Auction.find(params[:auction_id])
    @auction.reach_lowest_price
    redirect_to administration_auction_path(@auction)
  end

  def terminate
    @auction = Auction.find(params[:auction_id])
    @auction.terminate
    redirect_to administration_auction_path(@auction)
  end

  def sell_out
    @auction = Auction.find(params[:auction_id])
    @auction.sell_out
    redirect_to administration_auction_path(@auction)
  end

end

app/controllers/administration/common_controller.rb
class Administration::CommonController < ApplicationController
end

app/controllers/administration/purchases_controller.rb
class Administration::PurchasesController < Administration::CommonController

  def index
    @purchases = Purchase.all
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/administration/users_controller.rb
class Administration::UsersController < Administration::CommonController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to administration_users_path, notice: 'User created'
    else
      flash.now[:error] = 'User not created'
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
  end

end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController

  def index
    @auctions = Auction.all
  end

  def show
    @auction = Auction.find(params[:id])

    respond_to do |format|
      format.html {}
      format.js   {}
    end
  end

end

app/helpers/auctions_helper.rb
module AuctionsHelper

  def state_message_for(auction)
    if logged_in?
      if current_user.registered_for?(auction)
        if true # Add user active in auction check
          authorized_message_for(auction.state)
        else
          'Your participation in this auction has ended.'
        end
      else
        unauthorized_message_for(auction.state)
      end
    else
      unauthorized_message_for(auction.state)
    end
  end

  def authorized_message_for(state)
    case state
    when 'unscheduled'
      'Auction still not scheduled.'
    when 'scheduled'
      'Registered for auction. Waiting to start...'
    when 'running'
      'Auction running...'
    when 'waiting_for_active_users'
      'Waiting for active users ...'
    when 'reached_lowest_price'
      'Auction closed. Product lowest price reached.'
    when 'sold_out'
      'Auction closed. Product sold out.'
    when 'terminated'
      'Auction closed.'
    end
  end

  def unauthorized_message_for(state)
    case state
    when 'unscheduled'
      'Auction not scheduled.'
    when 'scheduled'
      'Registering for auction ...'
    when 'running'
      'Auction is running ...'
    when 'waiting_for_active_users'
      'Auction is running ...'
    when 'reached_lowest_price'
      'Auction closed.'
    when 'sold_out'
      'Auction closed.'
    when 'terminated'
      'Auction closed.'
    end
  end

end

app/views/administration/auctions/_auction_actions.html.erb
<%= content_tag :div, class: 'auction-actions' do %>
  <% @auction.state_events.each do |state| %>
    <%= form_for [:administration, @auction],
                  url: url_for(controller: 'auctions', action: state, auction_id: @auction.id),
                  method: :put do |f|
    %>
      <%= f.submit state %>
    <% end %>
  <% end %>
<% end %>

app/views/administration/auctions/_form.html.erb
_form.html.erb

app/views/administration/auctions/index.html.erb
<table border="1">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Description</th>
      <th>Start price</th>
      <th>End price</th>
      <th>Current price</th>
      <th>Store price</th>
      <th>Start quantity</th>
      <th>Current quantity</th>
      <th>State</th>
      <th>Start time</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @auctions.each do |auction| %>
      <tr>
        <td><%= auction.id %></td>
        <td><%= auction.title %></td>
        <td><%= auction.description %></td>
        <td><%= auction.start_price %></td>
        <td><%= auction.end_price %></td>
        <td><%= auction.current_price %></td>
        <td><%= auction.store_price %></td>
        <td><%= auction.start_quantity %></td>
        <td><%= auction.current_quantity %></td>
        <td><%= auction.state %></td>
        <td><%= auction.start_datetime %></td>
        <td><%= auction.created_at %></td>
        <td><%= auction.updated_at %></td>
        <td>Edit</td>
        <td>Delete</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New', new_administration_auction_path %>

app/views/administration/auctions/new.html.erb
<%= form_for [:administration, @auction] do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br/><br/>

  <%= f.label :description %>
  <%= f.text_field :description %>
  <br/><br/>

  <%= f.label :start_price %>
  <%= f.text_field :start_price %>
  <br/><br/>

  <%= f.label :end_price %>
  <%= f.text_field :end_price %>
  <br/><br/>

  <%= f.label :store_price %>
  <%= f.text_field :store_price %>
  <br/><br/>

  <%= f.label :start_quantity %>
  <%= f.text_field :start_quantity %>
  <br/><br/>

  <%= f.label :minimum_users_per_product %>
  <%= f.text_field :minimum_users_per_product %>
  <br/><br/>

  <%= f.label :maximum_users_per_product %>
  <%= f.text_field :maximum_users_per_product %>
  <br/><br/>

  <%= f.label :time_for_purchase %>
  <%= f.text_field :time_for_purchase %> (seconds)
  <br/><br/>

  <%= f.label :active_users_timeout %>
  <%= f.text_field :active_users_timeout %> (seconds)
  <br/><br/>

  <%= f.label :price_reduce_amount %>
  <%= f.text_field :price_reduce_amount %> (stotinki)
  <br/><br/>

  <%= f.label :price_reduce_pace %>
  <%= f.text_field :price_reduce_pace %> (seconds)
  <br/><br/>

  <%= f.label           :start_datetime %>
  <%= f.datetime_select :start_datetime %>
  <br/><br/>

  <%= f.submit :create %>
<% end %>

app/views/administration/auctions/show.html.erb
<%= render partial: 'auctions/auction_state',  locals: { auction: @auction } %>
<%= render partial: 'auctions/auction',        locals: { auction: @auction } %>
<%= render partial: 'auction_actions',         locals: { auction: @auction } %>

app/views/administration/auctions/show.js.erb
$('.auction-state').replaceWith('<%=j render partial: 'auctions/auction_state',  locals: { auction: @auction } %>');
$('.auction').replaceWith('<%=j render partial: 'auctions/auction', locals: { auction: @auction } %>');
$('.auction-actions').replaceWith('<%=j render partial: 'auction_actions', locals: { auction: @auction } %>');